name: gh-pages
on:
  push:
    branches:
      - master
jobs:
  compile-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.2
      - name: merge master
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch
          git checkout -b gh-pages origin/gh-pages
          git merge master --allow-unrelated-histories -Xtheirs
      - name: compile
        run: |
          npm i
          npm run prd
      - name: commit
        run: |
          git add -f out.js
          git add -f out.js.map
          git commit -m "commit compiled codes"
      - name: push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
        
